### ISSUE TITLE
XML Error on 72D launch of the modder 

### ISSUE THREAD

**Issue by xianthe** [SphereII/7D2DModLauncher#1]
![image](https://user-images.githubusercontent.com/279276/147735510-09c84d4a-e2a4-403c-80ff-7b0756536e4a.png)

Any idea how to fix this error on the XML /DTD issue on startup?

**Comment by SphereII** [comment]
The Mod Launcher is download a small database to the %TEMP% share. The error message seems to say its open already. If you are not running any other Mod Launcher instances, I'd suggest rebooting to clear the error.

Sometimes anti-virus will lock the file too, while it's scanning, and does not release it fast enough for the mod launcher to access it.

**Comment by xianthe** [comment]
I do not have AV. I've rebooted but will try again.

Also something else may be happening because this is not my User name : "kilpa"
INFO 1 _7D2DLauncher.frmMain - System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at _7D2DLauncher.frmMain.ReadXML(String strXMLFilePath) in C:\Users\kilpa\Documents\GitHub\7D2DModLauncher-Original\7D2DLauncher\7D2DLauncher\7D2DLauncher.cs:line 739

Where is the user path coming from?

**Comment by SphereII** [comment]
That's a bit of a different error.

In Windows Explorer, can you copy and paste this:   %APPDATA%\..\Roaming\7D2DModLauncher

Then edit the ModLauncher.txt

Look for a line that starts with:   RemoteServers=

is there anything there? You can safely delete that line, and try to restart the mod launcher
